import type { PlayerAttributes } from "../types/player-attributes";
import type { GroupedAttributes } from "../types/grouped-attributes";

export function groupPlayerAttributes(
  player: PlayerAttributes,
): GroupedAttributes {
  return {
    goalkeeping: {
      handling: player.handling,
      reflexes: player.reflexes,
      rushingOutTendency: player.rushingOutTendency,
      commandOfArea: player.commandOfArea,
      communication: player.communication,
      aerialReach: player.aerialReach,
      oneOnOnes: player.oneOnOnes,
      throwing: player.throwing,
      punching: player.punching,
      kicking: player.kicking,
      eccentricity: player.eccentricity,
    },
    technical: {
      crossing: player.crossing,
      technique: player.technique,
      tackling: player.tackling,
      heading: player.heading,
      marking: player.marking,
      longThrows: player.longThrows,
      corners: player.corners,
      dribbling: player.dribbling,
      freeKickTaking: player.freeKickTaking,
      penaltyTaking: player.penaltyTaking,
      finishing: player.finishing,
      firstTouch: player.firstTouch,
      longShots: player.longShots,
      passing: player.passing,
    },
    mental: {
      concentration: player.concentration,
      aggression: player.aggression,
      leadership: player.leadership,
      positioning: player.positioning,
      teamWork: player.teamWork,
      workRate: player.workRate,
      decisions: player.decisions,
      determination: player.determination,
      anticipation: player.anticipation,
      composure: player.composure,
      bravery: player.bravery,
      flair: player.flair,
      offTheBall: player.offTheBall,
      vision: player.vision,
    },
    physical: {
      acceleration: player.acceleration,
      pace: player.pace,
      stamina: player.stamina,
      strength: player.strength,
      naturalFitness: player.naturalFitness,
      balance: player.balance,
      jumpingReach: player.jumpingReach,
      agility: player.agility,
    },
    misc: {
      player: player.player,
      age: player.age,
      euNational: player.euNational,
      position: player.position,
      uniqueId: player.uniqueId,
      expires: player.expires,
      wage: player.wage,
      rightFoot: player.rightFoot,
      leftFoot: player.leftFoot,
      transferValueRange: player.transferValueRange,
    },
  };
}
